### PR TITLE
Use nox to build and clean docs

### PR DESCRIPTION
**Pull request by mdpiper**
This PR sets up [nox](https://nox.thea.codes/en/stable/) to build and clean the BMI documentation. Since the docs are built with [sphinx](https://www.sphinx-doc.org/en/master/), using nox makes it easier to handle dependencies.

Three nox sessions are defined:

* build-docs
* clean-docs
* nuke

### CODE REVIEW

**Comment by mdpiper** [comment]
This PR is narrowly defined for building and cleaning the docs. It might be a good idea to add sessions like

* lint
* clean

to `noxfile.py`, either in this PR or a subsequent one.

**Review by mcflugen — APPROVED** [review]
👍

**Comment by rmcd-mscb** [comment]
@mdpiper you could also setup nox to run pre-commit to lint and check your files. We run pre-commit both as a commit hook and in our tests.  https://code.usgs.gov/wma/nhgf/toolsteam/gdptools/-/blob/develop/noxfile.py#L127

**Comment by mcflugen** [comment]
@rmcd-mscb Exactly what I was thinking. We're big fans for *pre-commit* and do exactly what you're describing with most of our other repositories. There's not a lot of lint to be removed from a repository such as this one but there's always something!

**Pull request merged**
