### PR TITLE
Add contributed BMI language specs and examples

### LINKED ISSUE #108: Add support for Julia
The BMI should support Julia by including a language specification, a sample implementation, and documentation.

### PR DESCRIPTION
**Pull request by mdpiper**
This PR adds links in the documentation and the README to the community-contributed BMI language specifications and examples for Javascript and Julia.

Thank you to @visr (Julia) and @gregjewi and his colleagues (Javascript) for their contributions!

This resolves #108.

### CODE REVIEW

**Comment by mdpiper** [comment]
Here are the resulting docs: https://bmi.readthedocs.io/en/mdpiper-add-contributed-specs/.

Although I've tagged this for merge with lazy consensus, if anyone would like to review the language I've used, it would be helpful.

**Comment by mdpiper** [comment]
I'm sorry about all the monkeying with branches. I realized too late that I wanted to merge this PR into the `stable` branch, but I had started it from the `develop` branch.

**Comment by gregtucker** [comment]
👍

**Comment by mdpiper** [comment]
If I don't see any comments on this PR, I'll merge it by the end of the week.

**Pull request merged**
