### PR TITLE
Update URLs

### PR DESCRIPTION
**Pull request by mwtoews**
Mostly this is refreshing oldish non-secure `http:` URLs to modern ones.

Also update old `http://dx.doi.org/` DOI prefixes to `https://doi.org/`

### CODE REVIEW

**Comment by mdpiper** [comment]
@mwtoews Thanks for submitting this PR. I appreciate your help in keeping the docs fresh. Would you mind basing your commit off of `stable` instead of `develop`? We build the docs off of `stable`, and this contribution would be helpful to have there. I'll then merge `stable` into `develop`, which has the new features for the next version of BMI.

**Comment by mwtoews** [comment]
Ready now for `stable`.

(In a strange quirk, it seems that the commit needs to be pushed before switching the branch in this GitHub UI)

**Comment by mdpiper** [comment]
Awesome! Thanks for doing this. I've marked the PR for lazy consensus, so if no one has any comments on it, I'll merge it in a week or so.

As an aside, do you think the workflow I'm using (`stable` for docs and immediate fixes, merging into `develop` with new stuff for a future release) is OK? If you have any suggestions for improvement, I'm open to ideas.

**Review by mdpiper — APPROVED** [review]

**Comment by mwtoews** [comment]
There are so many git workflows and variations available, but I'm not always sure which is best, but from the perspective of ReadTheDocs merging to `stable` first seems fine. So long as it doesn't stray away from `develop`. (I typically use [`git cherry-pick`](https://git-scm.com/docs/git-cherry-pick) to put the same commit into multiple branches).

**Comment by mdpiper** [comment]
Cool! Thanks for your thoughts on this. I'm just trying to do no harm. And I haven't tried `git cherry-pick` before; I'll look into how I can use it.

**Pull request merged**
